#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_INFO                                100
#define DLG_MAIN                                101
#define ID_INFO_BOK                             40000
#define ID_MAIN_BEXECUTE                        40000
#define ID_MAIN_BINFO                           40001
#define ID_INFO_VERSION                         40002
#define ID_MAIN_BCANCEL                         40002
#define ID_INFO_SPLATFORM                       40003
#define ID_MAIN_CDESKTOP                        40003
#define ID_MAIN_CDOWNLOADS                      40004
#define ID_MAIN_CDOCUMENTS                      40005
#define ID_MAIN_CPITCTURES                      40006
#define ID_MAIN_CVIDEOS                         40007
#define ID_MAIN_CMUSIC                          40008
#define ID_MAIN_COBJECTS3D                      40009
#define ID_MAIN_CHISTORY                        40010
#define ID_MAIN_CRECENT                         40011
#define ID_MAIN_CFAVORITES                      40012
#define ID_MAIN_CLINKS                          40013
#define ID_MAIN_CINETCACHE                      40014
#define ID_MAIN_CINETCOOKIES                    40015
#define ID_MAIN_CSAVEGAMES                      40016
#define ID_MAIN_CSEARCHES                       40017
#define ID_MAIN_CCONTANCTS                      40018
#define ID_MAIN_CROAMING                        40019
#define ID_MAIN_CTEMP                           40020
#define ID_MAIN_EDESKTOP                        40021
#define ID_MAIN_EDOWNLOADS                      40022
#define ID_MAIN_EDOCUMENTS                      40023
#define ID_MAIN_EPITCTURES                      40024
#define ID_MAIN_EVIDEOS                         40025
#define ID_MAIN_EMUSIC                          40026
#define ID_MAIN_EOBJECTS3D                      40027
#define ID_MAIN_EHISTORY                        40028
#define ID_MAIN_ERECENT                         40029
#define ID_MAIN_EFAVORITES                      40030
#define ID_MAIN_ELINKS                          40031
#define ID_MAIN_EINETCACHE                      40032
#define ID_MAIN_EINETCOOKIES                    40033
#define ID_MAIN_ESAVEGAMES                      40034
#define ID_MAIN_ESEARCHES                       40035
#define ID_MAIN_ECONTANCTS                      40036
#define ID_MAIN_EROAMING                        40037
#define ID_MAIN_ETEMP                           40038
#define ID_MAIN_SDESKTOP                        40039
#define ID_MAIN_SDOWNLOADS                      40040
#define ID_MAIN_SDOCUMENTS                      40041
#define ID_MAIN_SPITCTURES                      40042
#define ID_MAIN_SVIDEOS                         40043
#define ID_MAIN_SMUSIC                          40044
#define ID_MAIN_SOBJECTS3D                      40045
#define ID_MAIN_SHISTORY                        40046
#define ID_MAIN_SRECENT                         40047
#define ID_MAIN_SFAVORITES                      40048
#define ID_MAIN_SLINKS                          40049
#define ID_MAIN_SINETCACHE                      40050
#define ID_MAIN_SINETCOOKIES                    40051
#define ID_MAIN_SSAVEGAMES                      40052
#define ID_MAIN_SSEARCHES                       40053
#define ID_MAIN_SCONTANCTS                      40054
#define ID_MAIN_SROAMING                        40055
#define ID_MAIN_STEMP                           40056
#define ID_MAIN_CSIGNOUT                        40057
#define ID_MAIN_RMOVE                           40058
#define ID_MAIN_RCOPY                           40059
#define ID_MAIN_RNOACTION                       40060
#define ID_MAIN_CCLEAR                          40061
#define ID_MAIN_ETARGETFOLDER                   40062
#define ID_MAIN_BBROWSE                         40063
#define ID_MAIN_CWINDEFAULT                     40064
#define ID_MAIN_CLOADCONFIG                     40065
#define ID_MAIN_SPLATFORM                       40066
