#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_MAIN                                101
#define DLG_INFO                                102
#define ID_INFO_SPLATFORM                       40000
#define ID_MAIN_BEXECUTE                        40000
#define ID_MAIN_EPITCTURES                      40001
#define ID_INFO_PIMAGE                          40002
#define ID_MAIN_BCANCEL                         40002
#define ID_INFO_VERSION                         40003
#define ID_MAIN_CDESKTOP                        40003
#define ID_INFO_BOK                             40004
#define ID_MAIN_CDOCUMENTS                      40004
#define ID_MAIN_CFAVORITES                      40005
#define ID_MAIN_CINETCACHE                      40006
#define ID_MAIN_CINETCOOKIES                    40007
#define ID_MAIN_CTEMP                           40008
#define ID_MAIN_CCONTANCTS                      40009
#define ID_MAIN_CDOWNLOADS                      40010
#define ID_MAIN_CLINKS                          40011
#define ID_MAIN_CSEARCHES                       40012
#define ID_MAIN_CVIDEOS                         40013
#define ID_MAIN_SPITCTURES                      40014
#define ID_MAIN_CMUSIC                          40015
#define ID_MAIN_CSAVEGAMES                      40016
#define ID_MAIN_EDESKTOP                        40017
#define ID_MAIN_EDOCUMENTS                      40018
#define ID_MAIN_EFAVORITES                      40019
#define ID_MAIN_EINETCACHE                      40020
#define ID_MAIN_EINETCOOKIES                    40021
#define ID_MAIN_ETEMP                           40022
#define ID_MAIN_ECONTANCTS                      40023
#define ID_MAIN_EDOWNLOADS                      40024
#define ID_MAIN_ELINKS                          40025
#define ID_MAIN_ESEARCHES                       40026
#define ID_MAIN_EVIDEOS                         40027
#define ID_MAIN_CPITCTURES                      40028
#define ID_MAIN_EMUSIC                          40029
#define ID_MAIN_ESAVEGAMES                      40030
#define ID_MAIN_SDESKTOP                        40031
#define ID_MAIN_SDOCUMENTS                      40032
#define ID_MAIN_SFAVORITES                      40033
#define ID_MAIN_SINETCACHE                      40034
#define ID_MAIN_SINETCOOKIES                    40035
#define ID_MAIN_STEMP                           40036
#define ID_MAIN_SCONTANCTS                      40037
#define ID_MAIN_SDOWNLOADS                      40038
#define ID_MAIN_SLINKS                          40039
#define ID_MAIN_SSEARCHES                       40040
#define ID_MAIN_SVIDEOS                         40041
#define ID_MAIN_CHISTORY                        40042
#define ID_MAIN_SMUSIC                          40043
#define ID_MAIN_SSAVEGAMES                      40044
#define ID_MAIN_CSIGNOUT                        40045
#define ID_MAIN_RMOVE                           40046
#define ID_MAIN_RCOPY                           40047
#define ID_MAIN_RNOACTION                       40048
#define ID_MAIN_CCLEAR                          40049
#define ID_MAIN_ETARGETFOLDER                   40050
#define ID_MAIN_BBROWSE                         40051
#define ID_MAIN_CWINDEFAULT                     40052
#define ID_MAIN_CLOADCONFIG                     40053
#define ID_MAIN_SPLATFORM                       40054
#define ID_MAIN_BINFO                           40055
#define ID_MAIN_EHISTORY                        40056
#define ID_MAIN_SHISTORY                        40057
#define ID_MAIN_CRECENT                         40058
#define ID_MAIN_ERECENT                         40059
#define ID_MAIN_SRECENT                         40060
#define ID_MAIN_COBJECTS3D                      40061
#define ID_MAIN_EOBJECTS3D                      40062
#define ID_MAIN_SOBJECTS3D                      40063
#define ID_MAIN_CSCREENSHOTS                    40064
#define ID_MAIN_ESCREENSHOTS                    40065
#define ID_MAIN_SSCREENSHOTS                    40066
